# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0672f7d0edb08eda0e3a435d7f252b41c62b6f7e6de73e12d6976c13b27ec61e3a39bce930d2fa786c89cb844744f0c15c2a18a355aa1a81548729b395ce198

test:
  secret_key_base: a4aee53f7c14627aa28dde4c4199e78e5638ebe342961ee6afa199946e11fe3a31daea8118d4fe63c5ff3bcb36d09b36a4844aceafd11aba661d3a4fd23354a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
